root: true

parser: '@typescript-eslint/parser'

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - prettier

plugins:
  - '@typescript-eslint'
  - prettier

parserOptions:
  ecmaVersion: 2021
  sourceType: module

rules:
  prettier/prettier:
    - warn
    - singleQuote: true
  
  '@typescript-eslint/no-unused-vars':
    - warn
    - argsIgnorePattern: '^_$'
